name: Build Mac OS 13 (Intel) DUMB

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: Linguistica.py
          mode: app
          enable-plugins: pyside6
          include-data-dir: resources=resources
          macos-app-icon: resources/images/icon.png

      - name: Build Installer
        run: |
          mkdir build/dmg_source_folder
          mv build/Linguistica.app build/dmg_source_folder/Linguistica.app
          osascript -e 'tell application "Finder" to make new alias at (POSIX file "/Applications") to (POSIX file "/Applications")'
          mv /Applications/Applications build/dmg_source_folder/Applications
          mac_os/create-dmg/create-dmg --icon Linguistica.app 64 96 --icon Applications 192 96 --icon-size 64 --no-internet-enable --text-size 14 --window-size 343 256 build/Linguistica_Installer.dmg build/dmg_source_folder

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/dmg_source_folder/*.app/**/*
            build/*.dmg
          include-hidden-files: true
